services:
  database:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: todolist
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - database_data:/var/lib/mysql:rwf
    networks:
      - symfony

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - symfony
    depends_on:
      database:
        condition: service_healthy
    command: sh -c "
      composer install && \
      until mysqladmin ping -h database --silent; do echo 'Waiting for database connection...'; sleep 2; done && \
      php bin/console doctrine:database:create --if-not-exists && \
      php bin/console doctrine:migrations:migrate --no-interaction && \
      php /var/www/html/import_csv.php && php-fpm"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - symfony

volumes:
  database_data:

networks:
  symfony:
